//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chat.DataAccessLayer.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int Id { get; set; }
        public string Text { get; set; }
        public int UserIdFrom { get; set; }
        public int UserIdTo { get; set; }
        public System.DateTime CreatedOn { get; set; }
    
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
    }
}
